home/urls.py
from django.urls import path
from home import views

urlpatterns = [
    path('', views.home, name="home"),
    path('home/', views.home, name="homes"),
    path('about/', views.aboutus, name='aboutus'),
    path('contact/', views.contactus, name='contact'),
    # path('faq/', views.faq, name='faq'),
    # path('gallery/', views.gallery, name='gallery'),
    # path('pricing/', views.pricing, name='pricing'),
    path('about/', views.aboutus, name='aboutus'),
    path('contact/', views.contactus, name='contact'),
    path('faq/', views.faq, name='faq'),
    path('search/', views.search, name='search'),
    path('shop/', views.shop, name='shop'),
    path('category/', views.category, name='category'),
    path('search_auto/', views.search_auto, name='search_auto'),
    path('category/<int:id>/<slug:slug>', views.category_products, name='category_products'),
    path('product/<int:id>/<slug:slug>', views.product_detail, name='product_detail'),
    # path('ajaxtest/', views.ajaxtest, name='ajaxtest'),
    # path('ajaxpost/', views.ajaxpost, name='ajaxpost'),
    path('ajaxcolor/', views.ajaxcolor, name='ajaxcolor'),
    path('ajaxcolor/', views.ajaxcolor, name='ajaxcolor'),
]

order/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('addtoshopcart/<int:id>', views.addtoshopcart, name='addtoshopcart'),
    path('deletefromcart/<int:id>', views.deletefromcart, name='deletefromcart'),
    path('orderproduct/', views.orderproduct, name='orderproduct'),
]

weedcave/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from home import views
from order import views as OrderViews
from user import views as UserViews


urlpatterns = [

    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('product/', include('product.urls')),
    path('order/', include('order.urls')),
    path('user/', include('user.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('shopcart/', OrderViews.shopcart, name='shopcart'),
    # path('ajaxtest/', views.ajaxtest, name='ajaxtest'),
    # path('ajaxpost/', views.ajaxpost, name='ajaxpost'),
    path('ajaxcolor/', views.ajaxcolor, name='ajaxcolor'),
    path('ajaxcolor/', views.ajaxcolor, name='ajaxcolor'),
    path('login/', UserViews.login_form, name='login_form'),
    path('logout/', UserViews.logout_func, name='logout_func'),
    path('signup/', UserViews.signup_form, name='signup_form'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm

from product.models import Product, Variants


class ShopCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    variant = models.ForeignKey(Variants, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField()

    def __str__(self):
        return self.product.title

    @property
    def price(self):
        return (self.product.price)

    @property
    def amount(self):
        return (self.quantity * self.product.price)

    @property
    def varamount(self):
        return (self.quantity * self.variant.price)


class ShopCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity']


class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preparing', 'Preparing'),
        ('OnShipping', 'OnShipping'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=5, editable=False)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    total = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    adminnote = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.first_name


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'address', 'phone', 'city', 'country']


class OrderProduct(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Canceled', 'Canceled'),
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variant = models.ForeignKey(Variants, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.title

order/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.utils.crypto import get_random_string

from home.models import Setting
from order.models import ShopCart, ShopCartForm, OrderForm, Order, OrderProduct
from product.models import Category, Product, Variants


def home(request):
    return HttpResponse("order Page")

@login_required(login_url='/login')
def addtoshopcart(request,id):
    url = request.META.get('HTTP_REFERER')
    current_user = request.user
    variantid = request.POST.get('variantid')
    checkinproduct = ShopCart.objects.filter(product_id=id)
    checkinvariant = ShopCart.objects.filter(variant_id=variantid)

    if checkinproduct and checkinvariant:
        control = 1  # the product is in cart
    else:
        control = 0  # the product is not in cart

    if request.method == 'POST':
        form = ShopCartForm(request.POST)
        if form.is_valid():
            if control == 1:
                data = ShopCart.objects.get(product_id=id)
                data.quantity += form.cleaned_data['quantity']
                data.save()
            else:
                data = ShopCart()
                data.user_id = current_user.id
                data.product_id = id
                data.variant_id = variantid
                data.quantity = form.cleaned_data['quantity']
                data.save()
        messages.success(request, " Product Added to Shopping Cart ")
        return HttpResponseRedirect(url)

    else:  # if there is no post
        if control == 1:  # Update shopcart
            data = ShopCart.objects.get(product_id=id)
            data.quantity += 1
            data.save()  #
        else:
            data = ShopCart()
            data.user_id = current_user.id
            data.product_id = id
            data.quantity = 1
            data.variant_id = None
            data.save()
        messages.success(request, " Product Added To ShopCart")
        return HttpResponseRedirect(url)

@login_required(login_url='/login')
def shopcart(request):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    home = ShopCart.objects.filter(user_id=current_user.id)
    total = 0
    for rs in shopcart:
        if rs.product.variant == 'None':
            total += rs.product.price * rs.quantity
        else:
            total += rs.variant.price * rs.quantity

    context = {
        'shopcart': shopcart,
        'home': home,
        'setting': setting,
        'total': total,
        'category': category
    }

    return render(request, 'shopcarts.html', context)


def deletefromcart(request,id):
    ShopCart.objects.filter(id=id).delete()
    messages.success(request, "your item deleted! for Cart")
    return HttpResponseRedirect("/shopcart")

@login_required(login_url='/login')
def orderproduct(request):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    total = 0
    for rs in shopcart:
        if rs.product.variant == 'None':
            total += rs.product.price * rs.quantity
        else:
            total += rs.variant.price * rs.quantity

    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():

            # apply credit card infromation from the bank like api process
            data = Order()
            data.first_name = form.cleaned_data['first_name']
            data.last_name = form.cleaned_data['last_name']
            data.address = form.cleaned_data['address']
            data.city = form.cleaned_data['city']
            data.phone = form.cleaned_data['phone']
            data.user_id = current_user.id
            data.total = total
            data.ip = request.META.get('REMOTE_ADDR')
            ordercode = get_random_string(5).upper()
            data.code = ordercode
            data.save()

            for rs in shopcart:
                detail = OrderProduct()
                detail.order_id = data.id
                detail.product_id = rs.product_id
                detail.user_id = current_user.id
                detail.quantity = rs.quantity
                if rs.product.variant == 'None':
                    detail.price = rs.product.price
                else:
                    detail.price = rs.variant.price
                detail.variant_id = rs.variant_id
                detail.amount = rs.amount
                detail.save()

                if rs.product.variant == 'None':
                    product = Product.objects.get(id=rs.product_id)
                    product.amount -= rs.quantity
                    product.save()
            else:
                check = Variants.objects.filter(id=rs.product_id)
                if len(check) > 0:
                    variant = Variants.objects.get(id=rs.product_id)
                    variant.quantity -= rs.quantity
                    variant.save()

            ShopCart.objects.filter(user_id=current_user.id).delete()
            request.session['cart_items'] = 0
            messages.success(request, "Your Order has been completed. Thank static")
            return render(request, 'order_completed.html', {'ordercode': ordercode, 'category': category})
        else:
            messages.warning(request, form.errors)
            return HttpResponseRedirect("/order/orderproduct")

    form = OrderForm()
    # profile = UserProfile.objects.get(user_id=current_user.id)
    setting = Setting.objects.get(pk=1)
    context = {
        'shopcart': shopcart,
        'setting': setting,
        'total': total,
        'form': form,
#        'profile': profile,
        'category': category,
    }
    return render(request, 'order_form.html', context)

order/templates/order_completed.html
{% extends 'home-base.html' %}
{% load static %}
{% block title %}  {{ setting.title}}  {% endblock %}
{% block keywords %}   {{ setting.keywords}}  {% endblock %}


{% block content %}

		<div class="w3l_banner_nav_right">
<!-- payment -->
		<div class="privacy about">
			<h3>Order <span>Completed</span></h3>

	         <div class="checkout-right">
				<!--Horizontal Tab-->
        <div id="parentHorizontalTab">
<!--            <ul class="resp-tabs-list hor_1">-->
<!--				<li>Cash on delivery (COD)</li>-->
<!--                <li>Credit/Debit</li>-->
<!--                <li>Netbanking</li>-->
<!--                <li>Paypal Account</li>-->
<!--            </ul>-->
            <div class="resp-tabs-container hor_1">

           <div>
                <h4>your order has been been recieved will email or call and tell you the method of payment</h4>
                </div>
                <h4>Dear {{ user.first_name }} {{ user.last_name}}</h4>
                <h3>Your order is completed</h3>
                <br>
                <h4>Order Code : {{ ordercode }}</h4>
                <h3> Thank You</h3>
                <hr>


            </div>





                </div>

            </div>
        </div>

	<!--Plug-in Initialisation-->

	<!-- // Pay -->

			 </div>

		</div>
<!-- //payment -->
		</div>
		<div class="clearfix"></div>
	</div>
<!-- //banner -->


<!-- newsletter -->
	<div class="newsletter">
		<div class="container">
			<div class="w3agile_newsletter_left">
				<h3>sign up for our newsletter</h3>
			</div>
			<div class="w3agile_newsletter_right">
				<form action="#" method="post">
                       {% csrf_token %}
					<input type="email" name="Email" value="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}" required="">
					<input type="submit" value="subscribe now">
				</form>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
<!-- //newsletter -->

 {% endblock %}

order/templates/order_form.html
{% extends 'home-base.html' %}
{% load static %}
{% block title %}  {{ setting.title}}  {% endblock %}
{% block keywords %}   {{ setting.keywords}}  {% endblock %}


{% block content %}

		<div class="w3l_banner_nav_right">
<!-- about -->
            				<form  class="creditly-card-form agileinfo_form" action="" method="post">
                    {% csrf_token %}
		<div class="privacy about">
			<h3>Shopping <span>Cart</span></h3>

	      <div class="checkout-right">
					<h4>Your shopping cart contains: 
                         {% load myapptags %}
                                     {% shopcartcount user.id as count %}
                                    <span>{{ count }} Products</span>
              </h4>
				<table class="timetable_sub">
					<thead>
						<tr>
							<th>SL No.</th>
							<th>Product</th>
							<th>Quality</th>
							<th>Product Name</th>

							<th>Price</th>
							<th>Remove</th>
						</tr>
					</thead>
					<tbody>
                    {% for rs in shopcart %}
                    <tr class="rem1">
						<td class="invert">1</td>
						<td class="invert-image"><a href="/product/{{ rs.product.id }}/{{ rs.slug }}">
                             {% if rs.variant.image_id > 0 %}
                            <img src="{{ rs.variant.image }}" alt="" class="img-responsive">
                                {% else %}
                                <img src="{{ rs.product.image.url }}" alt="" class="img-responsive">
                                {% endif %}</a></td>
						<td class="invert">
							 <div class="quantity">
								<div class="quantity-select">
									<div class="entry value-minus">&nbsp;</div>
									<div class="entry value"><span>{{ rs.quantity}}</span></div>
									<div class="entry value-plus active">&nbsp;</div>
								</div>
							</div>
						</td>
						<td class="invert"><a href="/product/{{ rs.product.id }}/{{ rs.slug }}">{{ rs.product }} {{ rs.variant.size }}</a></td>

						<td class="invert">
                            {% if rs.product.variant == 'None' %}
                                ${{ rs.product.price }}
                                {% else %}
                                {{ rs.variant.price }}
                                {% endif %}
</td>
						<td class="invert">
							<div class="rem">
								<div class="close1"><a href="/order/deletefromcart/{{ rs.id }}" onclick="return confirm('Delete!! Are you sure?')">
                                </a> </div>
							</div>

						</td>
					</tr>
 {% endfor %}

				</tbody></table>
			</div>
			<div class="checkout-left">
				<div class="col-md-4 checkout-left-basket">
					<h4>Continue to basket</h4>
					<ul>
                          {% for rs in shopcart %}
						<li>{{ rs.product }} <i>-</i> <span> {% if rs.product.variant == 'None' %}
                                ${{ rs.product.price }}
                                {% else %}
                                {{ rs.variant.price }}
                                {% endif %} </span></li>
						<li>Sub Total<i>-</i> <span>$    {% if rs.product.variant == 'None' %}
                                ${{ rs.amount }}
                                {% else %}
                                {{ rs.varamount }}
                                {% endif %}
</span></li>
                         {% endfor %}
						<li>Total <i>-</i> <span>${{ total }}</span></li>
					</ul>
				</div>
				<div class="col-md-8 address_form_agile">
					  <h4>Add a new Details</h4>

									<section class="creditly-wrapper wthree, w3_agileits_wrapper">
										<div class="information-wrapper">
											<div class="first-row form-group">
												<div class="controls">
													<label class="control-label">First name: </label>
												 <input type="text" name="first_name" value="{{ user.first_name }}" class="form-control" maxlength="10"  id="id_first_name">
												</div>
                                                <div class="controls">
													<label class="control-label">Last name: </label>
												  <input type="text" name="last_name" value="{{ user.first_name }}" class="form-control" maxlength="10"  id="id_last_name">
												</div>
												<div class="w3_agileits_card_number_grids">
													<div class="w3_agileits_card_number_grid_left">
														<div class="controls">
															<label class="control-label">Mobile number:</label>
														     <input type="text" name="first_name" value="{{ profile.phone }}" class="form-control" maxlength="20" id="id-phone">
														</div>
													</div>
													<div class="w3_agileits_card_number_grid_right">
														<div class="controls">
															<label class="control-label">Country: </label>
														  <input type="text"name="country" value="{{ profile.country }}" class="form-control" maxlength="10" required id="id_country">
														</div>
													</div>
													<div class="clear"> </div>
												</div>
												<div class="controls">
													<label class="control-label">Town/City: </label>
												<input type="text" name="city" value="{{ profile.city }}" class="form-control" maxlength="150" id="city">
												</div>
													<div class="controls">
															<label class="control-label">Address type: </label>
												   <input type="text" placeholder="Street Address" class="form-control" name="address" value="{{ profile.address }}"  maxlength="150" id="id_address">

													</div>
											</div>
											<button type="submit" class="submit check_out">Place Order</button>
										</div>
									</section>
								
									<div class="checkout-right-basket">
<!--				        	<a href="/order/orderproduct">Check Out <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span></a>-->
			      	</div>
					</div>

				<div class="clearfix"> </div>

			</div>

		</div>
            </form>
<!-- //about -->
		</div>
		<div class="clearfix"></div>
	</div>
<!-- //banner -->


<!-- newsletter -->
	<div class="newsletter">
		<div class="container">
			<div class="w3agile_newsletter_left">
				<h3>sign up for our newsletter</h3>
			</div>
			<div class="w3agile_newsletter_right">
				<form >
                       {% csrf_token %}
					<input type="email" name="Email" value="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}" required="">
					<input type="submit" value="subscribe now">
				</form>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
<!-- //newsletter -->

 {% endblock %}

order/templates/shopcarts.html
{% extends 'home-base.html' %}
{% load static %}
{% block title %}  {{ setting.title}}  {% endblock %}
{% block keywords %}   {{ setting.keywords}}  {% endblock %}


{% block content %}

		<div class="w3l_banner_nav_right">
<!-- about -->
		<div class="privacy about">
			<h3>Shopping <span>Cart</span></h3>

	      <div class="checkout-right">
					<h4>Your shopping cart contains: 
                         {% load myapptags %}
                                     {% shopcartcount user.id as count %}
                                    <span>{{ count }} Products</span>
              </h4>
				<table class="timetable_sub">
					<thead>
						<tr>
							<th>SL No.</th>
							<th>Product</th>
							<th>Quality</th>
							<th>Product Name</th>

							<th>Price</th>
							<th>Remove</th>
						</tr>
					</thead>
					<tbody>
                    {% for rs in shopcart %}
                    <tr class="rem1">
						<td class="invert">1</td>
						<td class="invert-image"><a href="/product/{{ rs.product.id }}/{{ rs.slug }}">
                             {% if rs.variant.image_id > 0 %}
                            <img src="{{ rs.variant.image }}" alt="" class="img-responsive">
                                {% else %}
                                <img src="{{ rs.product.image.url }}" alt="" class="img-responsive">
                                {% endif %}</a></td>
						<td class="invert">
							 <div class="quantity">
								<div class="quantity-select">
									<div class="entry value-minus">&nbsp;</div>
									<div class="entry value"><span>{{ rs.quantity}}</span></div>
									<div class="entry value-plus active">&nbsp;</div>
								</div>
							</div>
						</td>
						<td class="invert"><a href="/product/{{ rs.product.id }}/{{ rs.slug }}">{{ rs.product }} {{ rs.variant.size }}</a></td>

						<td class="invert">
                            {% if rs.product.variant == 'None' %}
                                ${{ rs.product.price }}
                                {% else %}
                                {{ rs.variant.price }}
                                {% endif %}
</td>
						<td class="invert">
							<div class="rem">
								<div class="close1"><a href="/order/deletefromcart/{{ rs.id }}" onclick="return confirm('Delete!! Are you sure?')">
                                </a> </div>
							</div>

						</td>
					</tr>
 {% endfor %}

				</tbody></table>
			</div>
			<div class="checkout-left">
				<div class="col-md-4 checkout-left-basket">
					<h4>Continue to basket</h4>
					<ul>
                          {% for rs in shopcart %}
						<li>{{ rs.product }} <i>-</i> <span> {% if rs.product.variant == 'None' %}
                                ${{ rs.product.price }}
                                {% else %}
                                {{ rs.variant.price }}
                                {% endif %} </span></li>
						<li>Sub Total<i>-</i> <span>$    {% if rs.product.variant == 'None' %}
                                ${{ rs.amount }}
                                {% else %}
                                {{ rs.varamount }}
                                {% endif %}
</span></li>
                         {% endfor %}
						<li>Total <i>-</i> <span>${{ total }}</span></li>
					</ul>
				</div>
				<div class="col-md-8 address_form_agile">
<!--					  <h4>Add a new Details</h4>-->
<!--
				<form  class="creditly-card-form agileinfo_form" action="" method="post">
                    {% csrf_token %}
									<section class="creditly-wrapper wthree, w3_agileits_wrapper">
										<div class="information-wrapper">
											<div class="first-row form-group">
												<div class="controls">
													<label class="control-label">Full name: </label>
												 <input type="text" name="first_name" value="{{ user.first_name }}" class="form-control" maxlength="10"  id="id_first_name">
												</div>
												<div class="w3_agileits_card_number_grids">
													<div class="w3_agileits_card_number_grid_left">
														<div class="controls">
															<label class="control-label">Mobile number:</label>
														     <input type="text" name="first_name" value="{{ profile.phone }}" class="form-control" maxlength="20" id="id-phone">
														</div>
													</div>
													<div class="w3_agileits_card_number_grid_right">
														<div class="controls">
															<label class="control-label">Country: </label>
														  <input type="text"name="country" value="{{ profile.country }}" class="form-control" maxlength="10" required id="id_country">
														</div>
													</div>
													<div class="clear"> </div>
												</div>
												<div class="controls">
													<label class="control-label">Town/City: </label>
												<input type="text" name="city" value="{{ profile.city }}" class="form-control" maxlength="150" id="city">
												</div>
													<div class="controls">
															<label class="control-label">Address type: </label>
												   <input type="text" placeholder="Street Address" class="form-control" name="address" value="{{ profile.address }}"  maxlength="150" id="id_address">

													</div>
											</div>
											<button type="submit" class="submit check_out">Delivery to this Address</button>
										</div>
									</section>
								</form>
-->
									<div class="checkout-right-basket">
				        	<a href="/order/orderproduct">Check Out <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span></a>
			      	</div>
					</div>

				<div class="clearfix"> </div>

			</div>

		</div>
<!-- //about -->
		</div>
		<div class="clearfix"></div>
	</div>
<!-- //banner -->


<!-- newsletter -->
	<div class="newsletter">
		<div class="container">
			<div class="w3agile_newsletter_left">
				<h3>sign up for our newsletter</h3>
			</div>
			<div class="w3agile_newsletter_right">
				<form >
                       {% csrf_token %}
					<input type="email" name="Email" value="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}" required="">
					<input type="submit" value="subscribe now">
				</form>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
<!-- //newsletter -->

 {% endblock %}